### PR TITLE
chore: fix reviewers team

### PR DESCRIPTION
**Pull request by jeffmaury**

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM but the group misses some members like Axel and Tim  https://github.com/orgs/redhat-developer/teams/podman-desktop-reviewers

**Comment by lstocchi** [comment]
Could we use `@containers/podman-desktop-reviewers` even if it is a different organization?

**Comment by benoitf** [comment]
it seems the file is invalid (team is not having access)

**Comment by jeffmaury** [comment]
> LGTM but the group misses some members like Axel and Tim https://github.com/orgs/redhat-developer/teams/podman-desktop-reviewers

Florent removed them temporaly because they did not update their GitHub status

**Comment by jeffmaury** [comment]
> it seems the file is invalid (team is not having access)

Should be good now

**Comment by lstocchi** [comment]
> Florent removed them temporaly because they did not update their GitHub status

Ah right, i forgot. Ok 👍

**Review by benoitf — APPROVED** [review]

**Pull request merged**
